flags: {}
packages:
- '.'
- deps/gloss
- deps/gloss-rendering
# - location:
#     git: git@github.com:ardumont/gloss.git
#     commit: d227506556d8085957845b210e4d5d032b26f4df
#     # deps
#     valid-wanted: false
#     subdirs:
#       - gloss

extra-deps:
  - gloss-1.9.4.1
  - GLUT-2.7.0.2
  - OpenGL-2.13.0.0
  - gloss-rendering-1.9.3.1
  - GLURaw-1.5.0.1
  - ObjectName-1.1.0.0
  - OpenGLRaw-2.5.2.1
  - gloss-game-0.3.3.0
  - gloss-juicy-0.2

extra-include-dirs:
- /nix/store/52sm54lvpwnxwgxvq8alxa49syfwgxxl-xorg-sys-opengl-3/include
- /nix/store/6wgwcnqb8hmvn2smfzalkqg127aafghk-glu-9.0.0/include
- /nix/store/flbjdhyv91ad4x1w06060nfxyn49jgxs-freeglut-2.8.1/include
- /var/run/opengl-driver/include
- /nix/store/qgkv4wcgsjiqq0049r6cz1fk9mw6265n-zlib-1.2.8/include

extra-lib-dirs:
- /nix/store/52sm54lvpwnxwgxvq8alxa49syfwgxxl-xorg-sys-opengl-3/lib
- /nix/store/6wgwcnqb8hmvn2smfzalkqg127aafghk-glu-9.0.0/lib
- /nix/store/flbjdhyv91ad4x1w06060nfxyn49jgxs-freeglut-2.8.1/lib
- /var/run/opengl-driver/lib
- /nix/store/qgkv4wcgsjiqq0049r6cz1fk9mw6265n-zlib-1.2.8/lib

resolver: lts-3.2
